import { Book, Category, Author } from "./types";

export const CATEGORIES: Category[] = [
  { id: "fiction", name: "Fiction", icon: "📚" },
  { id: "romance", name: "Romance", icon: "💕" },
  { id: "science", name: "Science", icon: "🔬" },
  { id: "business", name: "Business", icon: "💼" },
  { id: "technology", name: "Technology", icon: "💻" },
  { id: "history", name: "History", icon: "📜" },
  { id: "self-development", name: "Self-Development", icon: "🚀" },
  { id: "fantasy", name: "Fantasy", icon: "🐉" },
];

export const MOCK_AUTHORS: Author[] = [
  {
    id: "1",
    name: "Sarah Mitchell",
    bio: "Bestselling author of contemporary fiction and romance novels.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
    books: 12,
  },
  {
    id: "2",
    name: "James Chen",
    bio: "Tech entrepreneur and author specializing in AI and future technologies.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
    books: 7,
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    bio: "Historian and Pulitzer Prize-winning author.",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop",
    books: 15,
  },
  {
    id: "4",
    name: "David Foster",
    bio: "Life coach and motivational speaker with 10+ years of experience.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop",
    books: 9,
  },
  {
    id: "5",
    name: "Alexandra Petrova",
    bio: "Award-winning fantasy author known for her immersive world-building.",
    avatar: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&h=150&fit=crop",
    books: 11,
  },
  {
    id: "6",
    name: "Marcus Johnson",
    bio: "Former hedge fund manager and bestselling business author.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop",
    books: 6,
  },
];

export const MOCK_BOOKS: Book[] = [
  {
    id: "1",
    title: "The Silent Echo",
    author: "Sarah Mitchell",
    authorId: "1",
    description: "A gripping tale of love, loss, and the resilience of the human spirit.",
    coverImage: "https://picsum.photos/300/450?random=1",
    category: "fiction",
    rating: 4.8,
    reviews: 1245,
    pages: 320,
    publishYear: 2024,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "2",
    title: "AI Revolution",
    author: "James Chen",
    authorId: "2",
    description: "Understanding the future of artificial intelligence and its impact on humanity.",
    coverImage: "https://picsum.photos/300/450?random=2",
    category: "technology",
    rating: 4.6,
    reviews: 892,
    pages: 410,
    publishYear: 2024,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "3",
    title: "Whispers of the Past",
    author: "Emily Rodriguez",
    authorId: "3",
    description: "A historical epic spanning generations of a family in 19th century Europe.",
    coverImage: "https://picsum.photos/300/450?random=3",
    category: "history",
    rating: 4.9,
    reviews: 2103,
    pages: 560,
    publishYear: 2023,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "4",
    title: "Master Your Mind",
    author: "David Foster",
    authorId: "4",
    description: "Practical strategies for personal growth and mental clarity.",
    coverImage: "https://picsum.photos/300/450?random=4",
    category: "self-development",
    rating: 4.5,
    reviews: 756,
    pages: 280,
    publishYear: 2024,
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "5",
    title: "Dragon's Keep",
    author: "Sarah Mitchell",
    authorId: "1",
    description: "An epic fantasy adventure in a world of magic and mystery.",
    coverImage: "https://picsum.photos/300/450?random=5",
    category: "fantasy",
    rating: 4.7,
    reviews: 1876,
    pages: 480,
    publishYear: 2023,
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "6",
    title: "Startup Success",
    author: "James Chen",
    authorId: "2",
    description: "From idea to IPO: building a billion-dollar company.",
    coverImage: "https://picsum.photos/300/450?random=6",
    category: "business",
    rating: 4.4,
    reviews: 523,
    pages: 340,
    publishYear: 2024,
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "7",
    title: "Midnight in Paris",
    author: "Sarah Mitchell",
    authorId: "1",
    description: "A romantic journey through the streets of the City of Light.",
    coverImage: "https://picsum.photos/300/450?random=7",
    category: "romance",
    rating: 4.6,
    reviews: 934,
    pages: 290,
    publishYear: 2024,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "8",
    title: "Quantum Computing",
    author: "James Chen",
    authorId: "2",
    description: "A beginner's guide to the next frontier of technology.",
    coverImage: "https://picsum.photos/300/450?random=8",
    category: "science",
    rating: 4.3,
    reviews: 678,
    pages: 380,
    publishYear: 2023,
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "9",
    title: "The Roman Empire",
    author: "Emily Rodriguez",
    authorId: "3",
    description: "A comprehensive history of Rome's rise and fall.",
    coverImage: "https://picsum.photos/300/450?random=9",
    category: "history",
    rating: 4.8,
    reviews: 1567,
    pages: 620,
    publishYear: 2022,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "10",
    title: "Atomic Habits",
    author: "David Foster",
    authorId: "4",
    description: "Tiny changes, remarkable results: build good habits and break bad ones.",
    coverImage: "https://picsum.photos/300/450?random=10",
    category: "self-development",
    rating: 4.9,
    reviews: 3421,
    pages: 320,
    publishYear: 2024,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "11",
    title: "Shadow Realm",
    author: "Alexandra Petrova",
    authorId: "5",
    description: "Book 1 of the Shadow Saga: an epic fantasy adventure.",
    coverImage: "https://picsum.photos/300/450?random=11",
    category: "fantasy",
    rating: 4.7,
    reviews: 2345,
    pages: 540,
    publishYear: 2023,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "12",
    title: "The Intelligent Investor",
    author: "Marcus Johnson",
    authorId: "6",
    description: "A timeless guide to value investing and wealth building.",
    coverImage: "https://picsum.photos/300/450?random=12",
    category: "business",
    rating: 4.8,
    reviews: 1890,
    pages: 420,
    publishYear: 2024,
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "13",
    title: "The Last Letter",
    author: "Sarah Mitchell",
    authorId: "1",
    description: "A heart-wrenching story of love and redemption.",
    coverImage: "https://picsum.photos/300/450?random=13",
    category: "romance",
    rating: 4.5,
    reviews: 876,
    pages: 310,
    publishYear: 2024,
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "14",
    title: "Machine Learning",
    author: "James Chen",
    authorId: "2",
    description: "A practical guide to building intelligent systems.",
    coverImage: "https://picsum.photos/300/450?random=14",
    category: "technology",
    rating: 4.6,
    reviews: 1123,
    pages: 480,
    publishYear: 2023,
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "15",
    title: "The Middle Ages",
    author: "Emily Rodriguez",
    authorId: "3",
    description: "A vivid portrait of life in medieval Europe.",
    coverImage: "https://picsum.photos/300/450?random=15",
    category: "history",
    rating: 4.7,
    reviews: 1234,
    pages: 490,
    publishYear: 2023,
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "16",
    title: "Mindfulness",
    author: "David Foster",
    authorId: "4",
    description: "Finding peace and purpose in the present moment.",
    coverImage: "https://picsum.photos/300/450?random=16",
    category: "self-development",
    rating: 4.4,
    reviews: 654,
    pages: 260,
    publishYear: 2024,
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "17",
    title: "Darkness Rising",
    author: "Alexandra Petrova",
    authorId: "5",
    description: "Book 2 of the Shadow Saga: the battle continues.",
    coverImage: "https://picsum.photos/300/450?random=17",
    category: "fantasy",
    rating: 4.8,
    reviews: 1987,
    pages: 580,
    publishYear: 2024,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "18",
    title: "Rich Dad Poor Dad",
    author: "Marcus Johnson",
    authorId: "6",
    description: "What the rich teach their kids about money.",
    coverImage: "https://picsum.photos/300/450?random=18",
    category: "business",
    rating: 4.5,
    reviews: 2109,
    pages: 330,
    publishYear: 2023,
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "19",
    title: "The Great Gatsby",
    author: "Sarah Mitchell",
    authorId: "1",
    description: "A modern retelling of the classic American novel.",
    coverImage: "https://picsum.photos/300/450?random=19",
    category: "fiction",
    rating: 4.6,
    reviews: 1456,
    pages: 280,
    publishYear: 2024,
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "20",
    title: "Python Programming",
    author: "James Chen",
    authorId: "2",
    description: "Learn Python from scratch with hands-on examples.",
    coverImage: "https://picsum.photos/300/450?random=20",
    category: "technology",
    rating: 4.7,
    reviews: 1345,
    pages: 450,
    publishYear: 2024,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "21",
    title: "The Civil War",
    author: "Emily Rodriguez",
    authorId: "3",
    description: "A definitive history of America's defining conflict.",
    coverImage: "https://picsum.photos/300/450?random=21",
    category: "history",
    rating: 4.9,
    reviews: 2567,
    pages: 680,
    publishYear: 2022,
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "22",
    title: "The Power of Now",
    author: "David Foster",
    authorId: "4",
    description: "A guide to spiritual enlightenment and living in the present.",
    coverImage: "https://picsum.photos/300/450?random=22",
    category: "self-development",
    rating: 4.8,
    reviews: 2890,
    pages: 290,
    publishYear: 2024,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "23",
    title: "Lightbringer",
    author: "Alexandra Petrova",
    authorId: "5",
    description: "Book 3 of the Shadow Saga: the epic conclusion.",
    coverImage: "https://picsum.photos/300/450?random=23",
    category: "fantasy",
    rating: 4.9,
    reviews: 2678,
    pages: 620,
    publishYear: 2024,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "24",
    title: "Zero to One",
    author: "Marcus Johnson",
    authorId: "6",
    description: "Notes on startups, or how to build the future.",
    coverImage: "https://picsum.photos/300/450?random=24",
    category: "business",
    rating: 4.6,
    reviews: 1789,
    pages: 310,
    publishYear: 2023,
    isFeatured: false,
    isTrending: false,
  },
];
