import { Book, Category, Author } from "./types";

export const CATEGORIES: Category[] = [
  { id: "fiction", name: "Fiction", icon: "📚" },
  { id: "romance", name: "Romance", icon: "💕" },
  { id: "science", name: "Science", icon: "🔬" },
  { id: "business", name: "Business", icon: "💼" },
  { id: "technology", name: "Technology", icon: "💻" },
  { id: "history", name: "History", icon: "📜" },
  { id: "self-development", name: "Self-Development", icon: "🚀" },
  { id: "fantasy", name: "Fantasy", icon: "🐉" },
];

export const MOCK_AUTHORS: Author[] = [
  {
    id: "1",
    name: "Sarah Mitchell",
    bio: "Bestselling author of contemporary fiction and romance novels.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
    books: 8,
  },
  {
    id: "2",
    name: "James Chen",
    bio: "Tech entrepreneur and author specializing in AI and future technologies.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
    books: 5,
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    bio: "Historian and Pulitzer Prize-winning author.",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop",
    books: 12,
  },
];

export const MOCK_BOOKS: Book[] = [
  {
    id: "1",
    title: "The Silent Echo",
    author: "Sarah Mitchell",
    authorId: "1",
    description: "A gripping tale of love, loss, and the resilience of the human spirit.",
    coverImage: "https://picsum.photos/300/450?random=1",
    category: "fiction",
    rating: 4.8,
    reviews: 1245,
    pages: 320,
    publishYear: 2024,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "2",
    title: "AI Revolution",
    author: "James Chen",
    authorId: "2",
    description: "Understanding the future of artificial intelligence and its impact on humanity.",
    coverImage: "https://picsum.photos/300/450?random=2",
    category: "technology",
    rating: 4.6,
    reviews: 892,
    pages: 410,
    publishYear: 2024,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "3",
    title: "Whispers of the Past",
    author: "Emily Rodriguez",
    authorId: "3",
    description: "A historical epic spanning generations of a family in 19th century Europe.",
    coverImage: "https://picsum.photos/300/450?random=3",
    category: "history",
    rating: 4.9,
    reviews: 2103,
    pages: 560,
    publishYear: 2023,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "4",
    title: "Master Your Mind",
    author: "David Foster",
    authorId: "4",
    description: "Practical strategies for personal growth and mental clarity.",
    coverImage: "https://picsum.photos/300/450?random=4",
    category: "self-development",
    rating: 4.5,
    reviews: 756,
    pages: 280,
    publishYear: 2024,
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "5",
    title: "Dragon's Keep",
    author: "Sarah Mitchell",
    authorId: "1",
    description: "An epic fantasy adventure in a world of magic and mystery.",
    coverImage: "https://picsum.photos/300/450?random=5",
    category: "fantasy",
    rating: 4.7,
    reviews: 1876,
    pages: 480,
    publishYear: 2023,
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "6",
    title: "Startup Success",
    author: "James Chen",
    authorId: "2",
    description: "From idea to IPO: building a billion-dollar company.",
    coverImage: "https://picsum.photos/300/450?random=6",
    category: "business",
    rating: 4.4,
    reviews: 523,
    pages: 340,
    publishYear: 2024,
    isFeatured: false,
    isTrending: false,
  },
];
